### ISSUE TITLE
Issues with Google App Engine Thread

### ISSUE THREAD

**Issue by paarapp** [firebase/geofire-java#11]
So we are using Google App Engine as our primary backend and we are planning to call Firebase from our GAE instance for users' realtime location.
It seems like the GAE is denying GeoFire library because the library is initializing a `Thread` when calling `GeoFire geoFire = new GeoFire(new Firebase(("address")));`. So initializing `Firebase` object is throwing an exception.
Is there a work around for this problem? 

Here is the stack trace:
```
[INFO] Jun 24, 2015 12:03:00 AM com.google.api.server.spi.SystemService invokeServiceMethod
[INFO] SEVERE: exception occurred while calling backed method
[INFO] java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
[INFO] 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
[INFO] 	at java.security.AccessController.checkPermission(AccessController.java:559)
[INFO] 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
[INFO] 	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkPermission(DevAppServerFactory.java:429)
[INFO] 	at com.google.appengine.tools.development.DevAppServerFactory$CustomSecurityManager.checkAccess(DevAppServerFactory.java:454)
[INFO] 	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
[INFO] 	at java.lang.Thread.init(Thread.java:391)
[INFO] 	at java.lang.Thread.init(Thread.java:349)
[INFO] 	at java.lang.Thread.<init>(Thread.java:675)
[INFO] 	at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:572)
[INFO] 	at com.firebase.client.utilities.DefaultRunLoop$FirebaseThreadFactory.newThread(DefaultRunLoop.java:20)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:610)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:924)
[INFO] 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1590)
[INFO] 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:333)
[INFO] 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:530)
[INFO] 	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:619)
[INFO] 	at com.firebase.client.utilities.DefaultRunLoop.scheduleNow(DefaultRunLoop.java:47)
[INFO] 	at com.firebase.client.core.Repo.scheduleNow(Repo.java:191)
[INFO] 	at com.firebase.client.core.Repo.<init>(Repo.java:67)
[INFO] 	at com.firebase.client.core.RepoManager.getLocalRepo(RepoManager.java:64)
[INFO] 	at com.firebase.client.core.RepoManager.getRepo(RepoManager.java:19)
[INFO] 	at com.firebase.client.Firebase.<init>(Firebase.java:182)
[INFO] 	at com.firebase.client.Firebase.<init>(Firebase.java:187)
[INFO] 	at com.firebase.client.Firebase.<init>(Firebase.java:165)
[INFO] 	at com.example.endpoint.UserEndpoint.setUserLocation(UserEndpoint.java:109)
```

**Comment by jwngr** [comment]
The paradigms for GAE and Firebase are quite different (request / response versus an always open websocket). If you are going to use Firebase in GAE, we typically suggest using the REST API. Unfortunately, we don't have a REST version of GeoFire.

Would you mind explaining how the whole flow goes for your app and why you cannot use the GeoFire client library on the client?

**Comment by paarapp** [comment]
Ah bummer. It's just a design decision we made. One backend endpoint from the app. 
I guess we will have to use it from the client. Thank you for your help!

**Comment by Whiteseeker** [comment]
I have the same issue while just calling: 
final Firebase firebase = new Firebase("https://"+ Constants.FIREBASE_ID +".firebaseio.com"); 
in GAE (in a task / java servlet)
It's super sad knowing that [blog post](https://cloud.google.com/solutions/mobile/firebase-app-engine-android-studio) by Google explain that : "Firebase recently updated its Java client library to run on App Engine. This means you don't have to call the raw REST interface, which makes writing backend logic for your apps easier."
I hope the firebase java sdk will be compatible with GAE soon (^_^) or that the task queue api (not cron job) will be available on firebase (^_^)

**Comment by benwulfe** [comment]
Hi Whiteseeker, what you are trying to do should work.  Most likely the reason you are seeing the issue is because either:
a) you have not included: com.google.appengine:appengine-api-1.0-sdk
   this dependency is necessary to bring in the GAE threadmanager to properly create threads.  If this isn't included, our client will not know its running inside GAE.

b) there may be cases where Threads are being created improperly *outside* of the jvm client itself.  This might appear in open source libraries built on top of Firebase.  Please post the callstack of the exception and we should be able to tell.  For example, the callstack listed above is in the jvm client proper and is fixed if the correct dependencies are included.

Let me know if I can help further and apologies for the delayed response.

**Comment by Whiteseeker** [comment]
Hi Benwulfe,
With the help of a couple of other people we found the issue.
In App Engine you can't create thread except if you are using a backend module (ie: you can't in the default module).
It took me about 4 days to refactor the code to separate the code and have a separate backend module for notification, but it now works fine.
It would be great if firebase sdk also had a way to be use without trying to create threads.
Maybe checking [ThreadManager](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/ThreadManager) and check for exceptions when creating thread, display a warning in logs, and fallback on a synchronous call.

**Comment by benwulfe** [comment]
Hi Damien.  I'm sorry this has given you trouble.  Unfortunately, allowing
the firebase jvm client to run on a frontend module isn't something that is
technically feasible at this time.
Also, using firebase on a frontend is arguably an anti-pattern because
firebase itself can be used as the communication channel to the backend (vs
say using cloud endpoints, you can simply store data in firebase and read
it in the backend).  Also using the sdk in an autoscaled frontend can end
up using many more connections to firebase, which can cause performance
issues.
