### ISSUE TITLE
Filtering location queries based on an external id

### ISSUE THREAD

**Issue by crocodile** [firebase/geofire-java#127]
I'd like to share my use cases as I am wondering if you have had similar challenges or considered such enhancement. And most importantly, whether you think my solution would work at all and is reasonable. Thanks in advance!

## Use case 1:
My app fetches user posts specific to the user's current location. So far all posts are meant for all users at the query location, but now I am looking to implement a new feature where some of the posts are  #only for specific users and not for everybody.

**The solution I am contemplating:**
1.) Let each client specify a user Id (probably when the GeoFire instance is created). For example let's say we have a user id '12345678'
2.) Modify the code in a way that, instead of 'g' in the data object the library would use the user id of the addressee whilst the value would still be the geohash.  

So this:
```
{  
   "g":"eud4ygjp56",
   "l":{  
      "0":"25.813594499999994",
      "1":"-8.1338558"
   }
}
```
would become this:
```
{  
   "12345678":"eud4ygjp56",
   "l":{  
      "0":"25.813594499999994",
      "1":"-8.1338558"
   }
}
```

and then in [GeoQuery.java](https://github.com/firebase/geofire-java) the library would do something like this:
```
Query firebaseQuery = databaseReference.orderByChild(userId).startAt(query.getStartValue()).endAt(query.getEndValue());
```

As a result I expect the query only returning posts which have the '12345678' child and ignore the rest.

## Use case 2:
* Allowing posts to be addressed to multiple recipients. In this case I would just add multiple user ids as children, whilst copying over the same geohash value to each of them.  (I could limit the maximum number of recipients should that become an issue. )
```
{  
   "12345678":"eud4ygjp56",
   "87654321":"eud4ygjp56",
   "12345679":"eud4ygjp56",
   "l":{  
      "0":"25.813594499999994",
      "1":"-8.1338558"
   }
}
```

## Use case 3:
* Querying for both public posts (i.e.: for everyone) and for the posts addressed to specific people. This is where I think it becomes messy. I guess for this I'd have to create 2 separate queries, then join the results in the client code, as I don't think there is any way of doing an OR query in Firebase. 

Thanks again for reading! I am hoping you'll tell me that this is not all reckless and crazy. 🤔🤓💻

**Comment by samtstern** [comment]
@crocodile thanks for the well-explained issue.  The first blocker here would be indexing.  Without the consistent `g` naming of the property, it will be impossible to index this efficiently.

Have you considered duplicating the entire location for each user?  So instead of storing the location at `/locations/foo` you would store it at `/locations/$userid/foo`?  It will make updating more expensive but one of the main tradeoffs when using a NoSQL database is that you often have cheap reads and expensive writes!

**Comment by crocodile** [comment]
@samtstern thanks for your reply! It did sound too good to be true, but I thought I'd still ask. I am going to change the design according to your suggestion. 

One other question if you have an other moment: Do you think for my use cases the FireStore db would be any more fitting? (Ignoring the fact for a moment that this library is integrated with the RTDB only.)

**Comment by samtstern** [comment]
Cloud Firestore would be able to handle that kind of query more efficiently
(since it has built in indexing on every document field) but that doesn't
mean it's right/wrong for you in general.

Its totally fine to use both in your application, RTDB where you require
GeoFire and Firestore in some other places.
