### ISSUE TITLE
What replaces  com.google.firebase.database.core.Repo in Firebase 3.0?

### ISSUE THREAD

**Issue by ErstwhileWork** [firebase/geofire-java#26]
I think I have resolved all other issues to use geofire-java in Firebase 3.0 .. but this one.

What is the new replacement for  com.google.firebase.database.core.Repo in the "new" world.

**Comment by puf** [comment]
Cross-post: http://stackoverflow.com/questions/37792608/for-firebase-3-0-what-is-the-replacement-for-com-google-firebase-database-core

**Comment by jwngr** [comment]
Also asked on the Firebase Google Group [here](https://groups.google.com/forum/#!msg/firebase-talk/RTBMfT_4N6c/qdX_5io8AAAJ_). Please do not cross post like this. It is generally considered bad etiquette since we spend a bunch of time just de-duplicating your posts.

I don't know the answer to your question, but I am going to close this issue and let an answer come from Stack Overflow.
