### ISSUE TITLE
Ionic 2 Integration

### ISSUE THREAD

**Issue by REPTILEHAUS** [firebase/geofire-java#63]
I cant seem to integrate this into an Ionic 2 app using webpack. is there any resources available for using it within Ionic ?

**Comment by jwngr** [comment]
I think you are using the [JavaScript version of GeoFire](https://github.com/firebase/geofire-js), not this one, the Java version. That being said, there are no resources on how to integrate this library with Ionic and/or webpack. If you are having issues with webpack, it may be due to https://github.com/firebase/geofire-js/issues/123, so you may have to use a `<script>` tag instead of a `require()`.

**Comment by REPTILEHAUS** [comment]
Cheers for that :) Ive been searching for examples on all versions so apologies I put this in the wrong issues pile. I came to that conclusion myself and its working.. will try and integrate it with the webpack flow though as I dont like adding extra script tags, but for now it works.
