### ISSUE TITLE
Support for Firestore?

### ISSUE THREAD

**Issue by nohe427** [firebase/geofire-java#78]
Firestore was released today.  Will he have support for Firestore (soon)?

**Comment by samtstern** [comment]
@nohe427 Firestore has support for the "GeoPoint" data type.  Eventually, Firestore will have support for native geo queries.  For this reason we're not going to invest in porting GeoFire to Firestore since it would only be a temporary solution.  We'll take that extra engineering effort and put it into the native queries.

**Comment by nohe427** [comment]
Thanks @samtstern!

**Comment by mtabasco** [comment]
Excellent!

**Comment by vanniktech** [comment]
Can be closed as the answer was answered. Might be worth mentioning this in the README though.

**Comment by PankajSavaliya** [comment]
Is there any update for geofire for firestore??
