### ISSUE TITLE
Return snapshot data in GeoQueryEventListener

### ISSUE THREAD

**Issue by vanniktech** [firebase/geofire-java#89]
Some thoughts / reasonings are already in this issue - #86.

In our fork we changed the listener so that we'll get the actual parsed object. What we provide into our forked GeoQuery is a parser that can `fun parse(dataSnapshot: DataSnapshot): T` with that we can get the actual parsed data already in the callbacks (`onKeyEntered`, `onKeyExited` & `onKeyMoved`).

I think it would make sense to find out of all of the use cases and then come up with a better listener API that is easy to grasp and use.

I'd propose to brainstorm about this and use this issue to track our thoughs and possible API proposals.

**Comment by samtstern** [comment]
@vanniktech 

Let's keep issues small in scope when possible.  So this issue can be about snapshot data and #86 describes another improvement.  We can make a meta-issue or a label to group them if you want.

In FirebaseUI we call what you're describing a `SnapshotParser` and it has basically the interface you mentioned.

I think it would be reasonable to return the `DataSnapshot` along with the key for listener events.  I don't think GeoFire needs to go as far as to turn the snapshot into model data, that comes with fun challenges like caching (since it's a somewhat expensive reflection operation) that are better left to the developer or other libraries.

The main question is should we:

- Make a new listener class so that this is not a breaking API change?
- Add it to the existing listener class?

**Comment by vanniktech** [comment]
Do we want to work towards 3.0.0 and make a few breaking changes or not? If so I'd vote to change the parameters. Otherwise, we could make it backwards compatible and deprecate the old ones in favor of the new ones and then with a 3.0.0 remove them.

**Comment by samtstern** [comment]
I think let's do this in two steps:

- In a non-major release, let's add a second kind of listener that also gets a `DataSnapshot` for those who structure their data like you do.
- Discuss if we can solve the other end of the problem (writing data and geo together) for developers.  If we encourage developers to store geo and model data together without being careful they will likely clobber the POJO data with model updates.  This probably means a combination of breaking API changes and guidance around security rules.

**Comment by vanniktech** [comment]
That's the next thing that I'll tackle in the coming days.

**Comment by samtstern** [comment]
This issue was fixed and released in `v2.2.0`.  Future changes on this topic should come with new issues.

**Comment by sanisloandras** [comment]
Hello!
I understand that there is a DatasnapshotGeoQueryEventListener, I tried it out and it works fine, but
please somebody tell me how to actually add additional to the same location where our geofire data is stored? 
The method setLocation(String key, GeoLocation location) receives a GeoLocation, which is a final class, and can not be extended, so I can not set my custom object. I could add my addition data after the onComplete is called, but that's bad for 2 reasons:
- if the geofire record is new, onDataEntered and onDataChanged is triggered
- if the geofire record is updated, onDataChanged might trigger 2 times

My goal is a data structure like this:
-nuP4jg9lZjUm0JWnyQR4ckRpEkL2 {
    g: "u2xue7j7ec";
   l: [];
   user: "my custom user data here"

**Comment by vanniktech** [comment]
The new API is meant for read only purposes.
